AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for IAM Account Password Policy, FinTech Guardrails'

Resources:
  IAMAccountPasswordPolicy:
    Type: AWS::IAM::AccountPasswordPolicy
    Properties:
      MinimumPasswordLength: 14
      RequireSymbols: true
      RequireNumbers: true
      RequireUppercaseCharacters: true
      RequireLowercaseCharacters: true
      AllowUsersToChangePassword: true
      MaxPasswordAge: 90
      PasswordReusePrevention: 24
      HardExpiry: false # Set to true to force password expiration at MaxPasswordAge. False means it expires, but users can keep using it until they log in again. For this exercise, false is acceptable.

Outputs:
  PasswordPolicyStatus:
    Description: 'Status of the IAM Account Password Policy'
    Value: 'IAM Password Policy deployed successfully.'